// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SiteItem site item
// swagger:model siteItem
type SiteItem struct {

	// id
	ID string `json:"_id,omitempty"`

	// attr hidden id
	AttrHiddenID string `json:"attr_hidden_id,omitempty"`

	// attr no delete
	AttrNoDelete bool `json:"attr_no_delete,omitempty"`

	// desc
	Desc string `json:"desc,omitempty"`

	// health
	Health []*SiteItemHealth `json:"health"`

	// name
	Name string `json:"name,omitempty"`

	// num new alarms
	NumNewAlarms int64 `json:"num_new_alarms,omitempty"`

	// role
	Role string `json:"role,omitempty"`
}

// Validate validates this site item
func (m *SiteItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHealth(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SiteItem) validateHealth(formats strfmt.Registry) error {

	if swag.IsZero(m.Health) { // not required
		return nil
	}

	for i := 0; i < len(m.Health); i++ {
		if swag.IsZero(m.Health[i]) { // not required
			continue
		}

		if m.Health[i] != nil {
			if err := m.Health[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("health" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SiteItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SiteItem) UnmarshalBinary(b []byte) error {
	var res SiteItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
