// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SiteItemHealth site item health
// swagger:model siteItemHealth
type SiteItemHealth struct {

	// num adopted
	NumAdopted int64 `json:"num_adopted,omitempty"`

	// num ap
	NumAp int64 `json:"num_ap,omitempty"`

	// num disabled
	NumDisabled int64 `json:"num_disabled,omitempty"`

	// num disconnected
	NumDisconnected int64 `json:"num_disconnected,omitempty"`

	// num guest
	NumGuest int64 `json:"num_guest,omitempty"`

	// num gw
	NumGw int64 `json:"num_gw,omitempty"`

	// num iot
	NumIot int64 `json:"num_iot,omitempty"`

	// num pending
	NumPending int64 `json:"num_pending,omitempty"`

	// num sw
	NumSw int64 `json:"num_sw,omitempty"`

	// num user
	NumUser int64 `json:"num_user,omitempty"`

	// rx bytes r
	RxBytesR int64 `json:"rx_bytes-r,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// subsystem
	Subsystem string `json:"subsystem,omitempty"`

	// tx bytes r
	TxBytesR int64 `json:"tx_bytes-r,omitempty"`
}

// Validate validates this site item health
func (m *SiteItemHealth) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SiteItemHealth) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SiteItemHealth) UnmarshalBinary(b []byte) error {
	var res SiteItemHealth
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
