// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSystemInfoParams creates a new GetSystemInfoParams object
// with the default values initialized.
func NewGetSystemInfoParams() *GetSystemInfoParams {
	var ()
	return &GetSystemInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemInfoParamsWithTimeout creates a new GetSystemInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSystemInfoParamsWithTimeout(timeout time.Duration) *GetSystemInfoParams {
	var ()
	return &GetSystemInfoParams{

		timeout: timeout,
	}
}

// NewGetSystemInfoParamsWithContext creates a new GetSystemInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSystemInfoParamsWithContext(ctx context.Context) *GetSystemInfoParams {
	var ()
	return &GetSystemInfoParams{

		Context: ctx,
	}
}

// NewGetSystemInfoParamsWithHTTPClient creates a new GetSystemInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSystemInfoParamsWithHTTPClient(client *http.Client) *GetSystemInfoParams {
	var ()
	return &GetSystemInfoParams{
		HTTPClient: client,
	}
}

/*GetSystemInfoParams contains all the parameters to send to the API endpoint
for the get system info operation typically these are written to a http.Request
*/
type GetSystemInfoParams struct {

	/*SiteName
	  the site name

	*/
	SiteName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get system info params
func (o *GetSystemInfoParams) WithTimeout(timeout time.Duration) *GetSystemInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system info params
func (o *GetSystemInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system info params
func (o *GetSystemInfoParams) WithContext(ctx context.Context) *GetSystemInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system info params
func (o *GetSystemInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get system info params
func (o *GetSystemInfoParams) WithHTTPClient(client *http.Client) *GetSystemInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get system info params
func (o *GetSystemInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiteName adds the siteName to the get system info params
func (o *GetSystemInfoParams) WithSiteName(siteName string) *GetSystemInfoParams {
	o.SetSiteName(siteName)
	return o
}

// SetSiteName adds the siteName to the get system info params
func (o *GetSystemInfoParams) SetSiteName(siteName string) {
	o.SiteName = siteName
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param site_name
	if err := r.SetPathParam("site_name", o.SiteName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
