// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSiteEventsParams creates a new GetSiteEventsParams object
// with the default values initialized.
func NewGetSiteEventsParams() *GetSiteEventsParams {
	var ()
	return &GetSiteEventsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSiteEventsParamsWithTimeout creates a new GetSiteEventsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSiteEventsParamsWithTimeout(timeout time.Duration) *GetSiteEventsParams {
	var ()
	return &GetSiteEventsParams{

		timeout: timeout,
	}
}

// NewGetSiteEventsParamsWithContext creates a new GetSiteEventsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSiteEventsParamsWithContext(ctx context.Context) *GetSiteEventsParams {
	var ()
	return &GetSiteEventsParams{

		Context: ctx,
	}
}

// NewGetSiteEventsParamsWithHTTPClient creates a new GetSiteEventsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSiteEventsParamsWithHTTPClient(client *http.Client) *GetSiteEventsParams {
	var ()
	return &GetSiteEventsParams{
		HTTPClient: client,
	}
}

/*GetSiteEventsParams contains all the parameters to send to the API endpoint
for the get site events operation typically these are written to a http.Request
*/
type GetSiteEventsParams struct {

	/*SiteName
	  the site name

	*/
	SiteName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get site events params
func (o *GetSiteEventsParams) WithTimeout(timeout time.Duration) *GetSiteEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get site events params
func (o *GetSiteEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get site events params
func (o *GetSiteEventsParams) WithContext(ctx context.Context) *GetSiteEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get site events params
func (o *GetSiteEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get site events params
func (o *GetSiteEventsParams) WithHTTPClient(client *http.Client) *GetSiteEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get site events params
func (o *GetSiteEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiteName adds the siteName to the get site events params
func (o *GetSiteEventsParams) WithSiteName(siteName string) *GetSiteEventsParams {
	o.SetSiteName(siteName)
	return o
}

// SetSiteName adds the siteName to the get site events params
func (o *GetSiteEventsParams) SetSiteName(siteName string) {
	o.SiteName = siteName
}

// WriteToRequest writes these params to a swagger request
func (o *GetSiteEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param site_name
	if err := r.SetPathParam("site_name", o.SiteName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
