// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/bah2830/unifi_api/pkg/models"
)

// GetSiteClientsReader is a Reader for the GetSiteClients structure.
type GetSiteClientsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSiteClientsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSiteClientsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetSiteClientsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSiteClientsOK creates a GetSiteClientsOK with default headers values
func NewGetSiteClientsOK() *GetSiteClientsOK {
	return &GetSiteClientsOK{}
}

/*GetSiteClientsOK handles this case with default header values.

successful site client list response
*/
type GetSiteClientsOK struct {
	Payload *models.GetSiteClientsResponse
}

func (o *GetSiteClientsOK) Error() string {
	return fmt.Sprintf("[GET /s/{site_name}/stat/sta][%d] getSiteClientsOK  %+v", 200, o.Payload)
}

func (o *GetSiteClientsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetSiteClientsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSiteClientsDefault creates a GetSiteClientsDefault with default headers values
func NewGetSiteClientsDefault(code int) *GetSiteClientsDefault {
	return &GetSiteClientsDefault{
		_statusCode: code,
	}
}

/*GetSiteClientsDefault handles this case with default header values.

Error response
*/
type GetSiteClientsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get site clients default response
func (o *GetSiteClientsDefault) Code() int {
	return o._statusCode
}

func (o *GetSiteClientsDefault) Error() string {
	return fmt.Sprintf("[GET /s/{site_name}/stat/sta][%d] getSiteClients default  %+v", o._statusCode, o.Payload)
}

func (o *GetSiteClientsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
