// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSiteHealthParams creates a new GetSiteHealthParams object
// with the default values initialized.
func NewGetSiteHealthParams() *GetSiteHealthParams {
	var ()
	return &GetSiteHealthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSiteHealthParamsWithTimeout creates a new GetSiteHealthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSiteHealthParamsWithTimeout(timeout time.Duration) *GetSiteHealthParams {
	var ()
	return &GetSiteHealthParams{

		timeout: timeout,
	}
}

// NewGetSiteHealthParamsWithContext creates a new GetSiteHealthParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSiteHealthParamsWithContext(ctx context.Context) *GetSiteHealthParams {
	var ()
	return &GetSiteHealthParams{

		Context: ctx,
	}
}

// NewGetSiteHealthParamsWithHTTPClient creates a new GetSiteHealthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSiteHealthParamsWithHTTPClient(client *http.Client) *GetSiteHealthParams {
	var ()
	return &GetSiteHealthParams{
		HTTPClient: client,
	}
}

/*GetSiteHealthParams contains all the parameters to send to the API endpoint
for the get site health operation typically these are written to a http.Request
*/
type GetSiteHealthParams struct {

	/*SiteName
	  the site name

	*/
	SiteName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get site health params
func (o *GetSiteHealthParams) WithTimeout(timeout time.Duration) *GetSiteHealthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get site health params
func (o *GetSiteHealthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get site health params
func (o *GetSiteHealthParams) WithContext(ctx context.Context) *GetSiteHealthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get site health params
func (o *GetSiteHealthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get site health params
func (o *GetSiteHealthParams) WithHTTPClient(client *http.Client) *GetSiteHealthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get site health params
func (o *GetSiteHealthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiteName adds the siteName to the get site health params
func (o *GetSiteHealthParams) WithSiteName(siteName string) *GetSiteHealthParams {
	o.SetSiteName(siteName)
	return o
}

// SetSiteName adds the siteName to the get site health params
func (o *GetSiteHealthParams) SetSiteName(siteName string) {
	o.SiteName = siteName
}

// WriteToRequest writes these params to a swagger request
func (o *GetSiteHealthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param site_name
	if err := r.SetPathParam("site_name", o.SiteName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
