// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/bah2830/unifi_api/pkg/models"
)

// GetNeighboringAccessPointsReader is a Reader for the GetNeighboringAccessPoints structure.
type GetNeighboringAccessPointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNeighboringAccessPointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetNeighboringAccessPointsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetNeighboringAccessPointsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetNeighboringAccessPointsOK creates a GetNeighboringAccessPointsOK with default headers values
func NewGetNeighboringAccessPointsOK() *GetNeighboringAccessPointsOK {
	return &GetNeighboringAccessPointsOK{}
}

/*GetNeighboringAccessPointsOK handles this case with default header values.

successful site access point list
*/
type GetNeighboringAccessPointsOK struct {
	Payload *models.GetNeighboringAccessPointsResponse
}

func (o *GetNeighboringAccessPointsOK) Error() string {
	return fmt.Sprintf("[GET /s/{site_name}/stat/rogueap][%d] getNeighboringAccessPointsOK  %+v", 200, o.Payload)
}

func (o *GetNeighboringAccessPointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetNeighboringAccessPointsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNeighboringAccessPointsDefault creates a GetNeighboringAccessPointsDefault with default headers values
func NewGetNeighboringAccessPointsDefault(code int) *GetNeighboringAccessPointsDefault {
	return &GetNeighboringAccessPointsDefault{
		_statusCode: code,
	}
}

/*GetNeighboringAccessPointsDefault handles this case with default header values.

Error response
*/
type GetNeighboringAccessPointsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get neighboring access points default response
func (o *GetNeighboringAccessPointsDefault) Code() int {
	return o._statusCode
}

func (o *GetNeighboringAccessPointsDefault) Error() string {
	return fmt.Sprintf("[GET /s/{site_name}/stat/rogueap][%d] getNeighboringAccessPoints default  %+v", o._statusCode, o.Payload)
}

func (o *GetNeighboringAccessPointsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
