// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSiteClientsParams creates a new GetSiteClientsParams object
// with the default values initialized.
func NewGetSiteClientsParams() *GetSiteClientsParams {
	var ()
	return &GetSiteClientsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSiteClientsParamsWithTimeout creates a new GetSiteClientsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSiteClientsParamsWithTimeout(timeout time.Duration) *GetSiteClientsParams {
	var ()
	return &GetSiteClientsParams{

		timeout: timeout,
	}
}

// NewGetSiteClientsParamsWithContext creates a new GetSiteClientsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSiteClientsParamsWithContext(ctx context.Context) *GetSiteClientsParams {
	var ()
	return &GetSiteClientsParams{

		Context: ctx,
	}
}

// NewGetSiteClientsParamsWithHTTPClient creates a new GetSiteClientsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSiteClientsParamsWithHTTPClient(client *http.Client) *GetSiteClientsParams {
	var ()
	return &GetSiteClientsParams{
		HTTPClient: client,
	}
}

/*GetSiteClientsParams contains all the parameters to send to the API endpoint
for the get site clients operation typically these are written to a http.Request
*/
type GetSiteClientsParams struct {

	/*SiteName
	  the site name

	*/
	SiteName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get site clients params
func (o *GetSiteClientsParams) WithTimeout(timeout time.Duration) *GetSiteClientsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get site clients params
func (o *GetSiteClientsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get site clients params
func (o *GetSiteClientsParams) WithContext(ctx context.Context) *GetSiteClientsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get site clients params
func (o *GetSiteClientsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get site clients params
func (o *GetSiteClientsParams) WithHTTPClient(client *http.Client) *GetSiteClientsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get site clients params
func (o *GetSiteClientsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiteName adds the siteName to the get site clients params
func (o *GetSiteClientsParams) WithSiteName(siteName string) *GetSiteClientsParams {
	o.SetSiteName(siteName)
	return o
}

// SetSiteName adds the siteName to the get site clients params
func (o *GetSiteClientsParams) SetSiteName(siteName string) {
	o.SiteName = siteName
}

// WriteToRequest writes these params to a swagger request
func (o *GetSiteClientsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param site_name
	if err := r.SetPathParam("site_name", o.SiteName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
