// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNeighboringAccessPointsParams creates a new GetNeighboringAccessPointsParams object
// with the default values initialized.
func NewGetNeighboringAccessPointsParams() *GetNeighboringAccessPointsParams {
	var ()
	return &GetNeighboringAccessPointsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNeighboringAccessPointsParamsWithTimeout creates a new GetNeighboringAccessPointsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNeighboringAccessPointsParamsWithTimeout(timeout time.Duration) *GetNeighboringAccessPointsParams {
	var ()
	return &GetNeighboringAccessPointsParams{

		timeout: timeout,
	}
}

// NewGetNeighboringAccessPointsParamsWithContext creates a new GetNeighboringAccessPointsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNeighboringAccessPointsParamsWithContext(ctx context.Context) *GetNeighboringAccessPointsParams {
	var ()
	return &GetNeighboringAccessPointsParams{

		Context: ctx,
	}
}

// NewGetNeighboringAccessPointsParamsWithHTTPClient creates a new GetNeighboringAccessPointsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNeighboringAccessPointsParamsWithHTTPClient(client *http.Client) *GetNeighboringAccessPointsParams {
	var ()
	return &GetNeighboringAccessPointsParams{
		HTTPClient: client,
	}
}

/*GetNeighboringAccessPointsParams contains all the parameters to send to the API endpoint
for the get neighboring access points operation typically these are written to a http.Request
*/
type GetNeighboringAccessPointsParams struct {

	/*SiteName
	  the site name

	*/
	SiteName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get neighboring access points params
func (o *GetNeighboringAccessPointsParams) WithTimeout(timeout time.Duration) *GetNeighboringAccessPointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get neighboring access points params
func (o *GetNeighboringAccessPointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get neighboring access points params
func (o *GetNeighboringAccessPointsParams) WithContext(ctx context.Context) *GetNeighboringAccessPointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get neighboring access points params
func (o *GetNeighboringAccessPointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get neighboring access points params
func (o *GetNeighboringAccessPointsParams) WithHTTPClient(client *http.Client) *GetNeighboringAccessPointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get neighboring access points params
func (o *GetNeighboringAccessPointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiteName adds the siteName to the get neighboring access points params
func (o *GetNeighboringAccessPointsParams) WithSiteName(siteName string) *GetNeighboringAccessPointsParams {
	o.SetSiteName(siteName)
	return o
}

// SetSiteName adds the siteName to the get neighboring access points params
func (o *GetNeighboringAccessPointsParams) SetSiteName(siteName string) {
	o.SiteName = siteName
}

// WriteToRequest writes these params to a swagger request
func (o *GetNeighboringAccessPointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param site_name
	if err := r.SetPathParam("site_name", o.SiteName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
