// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSitesListParams creates a new SitesListParams object
// with the default values initialized.
func NewSitesListParams() *SitesListParams {

	return &SitesListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSitesListParamsWithTimeout creates a new SitesListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSitesListParamsWithTimeout(timeout time.Duration) *SitesListParams {

	return &SitesListParams{

		timeout: timeout,
	}
}

// NewSitesListParamsWithContext creates a new SitesListParams object
// with the default values initialized, and the ability to set a context for a request
func NewSitesListParamsWithContext(ctx context.Context) *SitesListParams {

	return &SitesListParams{

		Context: ctx,
	}
}

// NewSitesListParamsWithHTTPClient creates a new SitesListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSitesListParamsWithHTTPClient(client *http.Client) *SitesListParams {

	return &SitesListParams{
		HTTPClient: client,
	}
}

/*SitesListParams contains all the parameters to send to the API endpoint
for the sites list operation typically these are written to a http.Request
*/
type SitesListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the sites list params
func (o *SitesListParams) WithTimeout(timeout time.Duration) *SitesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sites list params
func (o *SitesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sites list params
func (o *SitesListParams) WithContext(ctx context.Context) *SitesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sites list params
func (o *SitesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sites list params
func (o *SitesListParams) WithHTTPClient(client *http.Client) *SitesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sites list params
func (o *SitesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SitesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
