// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/bah2830/unifi_api/pkg/models"
)

// SitesListReader is a Reader for the SitesList structure.
type SitesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SitesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSitesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewSitesListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSitesListOK creates a SitesListOK with default headers values
func NewSitesListOK() *SitesListOK {
	return &SitesListOK{}
}

/*SitesListOK handles this case with default header values.

Site list response
*/
type SitesListOK struct {
	Payload *models.GetSitesListResponse
}

func (o *SitesListOK) Error() string {
	return fmt.Sprintf("[GET /self/sites][%d] sitesListOK  %+v", 200, o.Payload)
}

func (o *SitesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetSitesListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSitesListDefault creates a SitesListDefault with default headers values
func NewSitesListDefault(code int) *SitesListDefault {
	return &SitesListDefault{
		_statusCode: code,
	}
}

/*SitesListDefault handles this case with default header values.

Error response
*/
type SitesListDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the sites list default response
func (o *SitesListDefault) Code() int {
	return o._statusCode
}

func (o *SitesListDefault) Error() string {
	return fmt.Sprintf("[GET /self/sites][%d] SitesList default  %+v", o._statusCode, o.Payload)
}

func (o *SitesListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
