// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/bah2830/unifi_api/pkg/models"
)

// SitesListDetailsReader is a Reader for the SitesListDetails structure.
type SitesListDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SitesListDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSitesListDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewSitesListDetailsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSitesListDetailsOK creates a SitesListDetailsOK with default headers values
func NewSitesListDetailsOK() *SitesListDetailsOK {
	return &SitesListDetailsOK{}
}

/*SitesListDetailsOK handles this case with default header values.

Site list response
*/
type SitesListDetailsOK struct {
	Payload *models.GetSitesListResponse
}

func (o *SitesListDetailsOK) Error() string {
	return fmt.Sprintf("[GET /stat/sites][%d] sitesListDetailsOK  %+v", 200, o.Payload)
}

func (o *SitesListDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetSitesListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSitesListDetailsDefault creates a SitesListDetailsDefault with default headers values
func NewSitesListDetailsDefault(code int) *SitesListDetailsDefault {
	return &SitesListDetailsDefault{
		_statusCode: code,
	}
}

/*SitesListDetailsDefault handles this case with default header values.

Error response
*/
type SitesListDetailsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the sites list details default response
func (o *SitesListDetailsDefault) Code() int {
	return o._statusCode
}

func (o *SitesListDetailsDefault) Error() string {
	return fmt.Sprintf("[GET /stat/sites][%d] SitesListDetails default  %+v", o._statusCode, o.Payload)
}

func (o *SitesListDetailsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
